version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_DB: financa_facil
      POSTGRES_USER: app_admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
